using Godot;
using System;
using System.Collections.Generic;

public partial class TextureAtlasHandler : Node
{
	/* this variable holds atlas info for atlases that can be loaded */
	public static Dictionary<string, AtlasInfo> AtlasFrameSets = new Dictionary<string, AtlasInfo>()
	{
		{"charactera/face_front", new AtlasInfo("charactera/face_front", 570, 569)},
		{"charactera/beards/frame1/beard_long", new AtlasInfo("charactera/beards/frame1/beard_long", 570, 619)},
		{"charactera/beards/frame1/beard_medium", new AtlasInfo("charactera/beards/frame1/beard_medium", 570, 619)},
		{"charactera/beards/frame1/beard_short", new AtlasInfo("charactera/beards/frame1/beard_short", 570, 619)},
		{"charactera/beards/frame1/chin_curtain", new AtlasInfo("charactera/beards/frame1/chin_curtain", 570, 619)},
		{"charactera/beards/frame1/fancy_stache", new AtlasInfo("charactera/beards/frame1/fancy_stache", 570, 619)},
		{"charactera/beards/frame1/goatee", new AtlasInfo("charactera/beards/frame1/goatee", 570, 619)},
		{"charactera/beards/frame1/pencil_stache", new AtlasInfo("charactera/beards/frame1/pencil_stache", 570, 619)},
		{"charactera/beards/frame1/puberty_stache", new AtlasInfo("charactera/beards/frame1/puberty_stache", 570, 619)},
		{"charactera/beards/frame1/scruffy_beard", new AtlasInfo("charactera/beards/frame1/scruffy_beard", 570, 619)},
		{"charactera/beards/frame1/scruffy_beard_long", new AtlasInfo("charactera/beards/frame1/scruffy_beard_long", 570, 619)},
		{"charactera/beards/frame1/scruffy_chin", new AtlasInfo("charactera/beards/frame1/scruffy_chin", 570, 619)},
		{"charactera/beards/frame1/scruffy_goatee", new AtlasInfo("charactera/beards/frame1/scruffy_goatee", 570, 619)},
		{"charactera/beards/frame1/scruffy_stache", new AtlasInfo("charactera/beards/frame1/scruffy_stache", 570, 619)},
		{"charactera/beards/frame1/sideburns", new AtlasInfo("charactera/beards/frame1/sideburns", 570, 619)},
		{"charactera/beards/frame1/thin_stache", new AtlasInfo("charactera/beards/frame1/thin_stache", 570, 619)},
		{"charactera/beards/frame2/beard_long", new AtlasInfo("charactera/beards/frame2/beard_long", 570, 619)},
		{"charactera/beards/frame2/beard_medium", new AtlasInfo("charactera/beards/frame2/beard_medium", 570, 619)},
		{"charactera/beards/frame2/beard_short", new AtlasInfo("charactera/beards/frame2/beard_short", 570, 619)},
		{"charactera/beards/frame2/chin_curtain", new AtlasInfo("charactera/beards/frame2/chin_curtain", 570, 619)},
		{"charactera/beards/frame2/fancy_stache", new AtlasInfo("charactera/beards/frame2/fancy_stache", 570, 619)},
		{"charactera/beards/frame2/goatee", new AtlasInfo("charactera/beards/frame2/goatee", 570, 619)},
		{"charactera/beards/frame2/pencil_stache", new AtlasInfo("charactera/beards/frame2/pencil_stache", 570, 619)},
		{"charactera/beards/frame2/puberty_stache", new AtlasInfo("charactera/beards/frame2/puberty_stache", 570, 619)},
		{"charactera/beards/frame2/scruffy_beard", new AtlasInfo("charactera/beards/frame2/scruffy_beard", 570, 619)},
		{"charactera/beards/frame2/scruffy_beard_long", new AtlasInfo("charactera/beards/frame2/scruffy_beard_long", 570, 619)},
		{"charactera/beards/frame2/scruffy_chin", new AtlasInfo("charactera/beards/frame2/scruffy_chin", 570, 619)},
		{"charactera/beards/frame2/scruffy_goatee", new AtlasInfo("charactera/beards/frame2/scruffy_goatee", 570, 619)},
		{"charactera/beards/frame2/scruffy_stache", new AtlasInfo("charactera/beards/frame2/scruffy_stache", 570, 619)},
		{"charactera/beards/frame2/sideburns", new AtlasInfo("charactera/beards/frame2/sideburns", 570, 619)},
		{"charactera/beards/frame2/thin_stache", new AtlasInfo("charactera/beards/frame2/thin_stache", 570, 619)},
		{"charactera/body/frame1", new AtlasInfo("charactera/body/frame1", 302, 391)},
		{"charactera/body/frame2", new AtlasInfo("charactera/body/frame2", 302, 391)},
		{"charactera/body/frame3", new AtlasInfo("charactera/body/frame3", 302, 391)},
		{"charactera/body/frame4", new AtlasInfo("charactera/body/frame4", 378, 376)},
		{"charactera/clothes/dress/frame1", new AtlasInfo("charactera/clothes/dress/frame1", 384, 406)},
		{"charactera/clothes/dress/frame2", new AtlasInfo("charactera/clothes/dress/frame2", 384, 406)},
		{"charactera/clothes/dress/frame3", new AtlasInfo("charactera/clothes/dress/frame3", 384, 406)},
		{"charactera/clothes/dress/frame4", new AtlasInfo("charactera/clothes/dress/frame4", 302, 391)},
		{"charactera/clothes/dress/frame5", new AtlasInfo("charactera/clothes/dress/frame5", 302, 391)},
		{"charactera/clothes/dress/frame6", new AtlasInfo("charactera/clothes/dress/frame6", 302, 391)},
		{"charactera/clothes/dress/frame7", new AtlasInfo("charactera/clothes/dress/frame7", 399, 408)},
		{"charactera/clothes/dress/frame8", new AtlasInfo("charactera/clothes/dress/frame8", 399, 408)},
		{"charactera/clothes/dress/frame9", new AtlasInfo("charactera/clothes/dress/frame9", 399, 408)},
		{"charactera/clothes/hoodie/frame1", new AtlasInfo("charactera/clothes/hoodie/frame1", 377, 412)},
		{"charactera/clothes/hoodie/frame2", new AtlasInfo("charactera/clothes/hoodie/frame2", 377, 412)},
		{"charactera/clothes/hoodie/frame3", new AtlasInfo("charactera/clothes/hoodie/frame3", 377, 412)},
		{"charactera/clothes/hoodie/frame4", new AtlasInfo("charactera/clothes/hoodie/frame4", 304, 410)},
		{"charactera/clothes/hoodie/frame5", new AtlasInfo("charactera/clothes/hoodie/frame5", 304, 410)},
		{"charactera/clothes/hoodie/frame6", new AtlasInfo("charactera/clothes/hoodie/frame6", 304, 410)},
		{"charactera/clothes/hoodie/frame7", new AtlasInfo("charactera/clothes/hoodie/frame7", 377, 410)},
		{"charactera/clothes/hoodie/frame8", new AtlasInfo("charactera/clothes/hoodie/frame8", 377, 410)},
		{"charactera/clothes/hoodie/frame9", new AtlasInfo("charactera/clothes/hoodie/frame9", 377, 410)},
		{"charactera/clothes/jeans/front", new AtlasInfo("charactera/clothes/jeans/front", 399, 408)},
		{"charactera/clothes/jeans/side", new AtlasInfo("charactera/clothes/jeans/side", 304, 390)},
		{"charactera/clothes/shirt/frame1", new AtlasInfo("charactera/clothes/shirt/frame1", 385, 409)},
		{"charactera/clothes/shirt/frame2", new AtlasInfo("charactera/clothes/shirt/frame2", 385, 408)},
		{"charactera/clothes/shirt/frame3", new AtlasInfo("charactera/clothes/shirt/frame3", 385, 408)},
		{"charactera/clothes/shirt/frame4", new AtlasInfo("charactera/clothes/shirt/frame4", 302, 391)},
		{"charactera/clothes/shirt/frame5", new AtlasInfo("charactera/clothes/shirt/frame5", 302, 391)},
		{"charactera/clothes/shirt/frame6", new AtlasInfo("charactera/clothes/shirt/frame6", 302, 391)},
		{"charactera/clothes/shirt/frame7", new AtlasInfo("charactera/clothes/shirt/frame7", 399, 408)},
		{"charactera/clothes/shirt/frame8", new AtlasInfo("charactera/clothes/shirt/frame8", 399, 408)},
		{"charactera/clothes/shirt/frame9", new AtlasInfo("charactera/clothes/shirt/frame9", 399, 408)},
		{"charactera/clothes/tshirt/frame1", new AtlasInfo("charactera/clothes/tshirt/frame1", 399, 408)},
		{"charactera/clothes/tshirt/frame2", new AtlasInfo("charactera/clothes/tshirt/frame2", 399, 408)},
		{"charactera/clothes/tshirt/frame3", new AtlasInfo("charactera/clothes/tshirt/frame3", 399, 408)},
		{"charactera/clothes/tshirt/frame4", new AtlasInfo("charactera/clothes/tshirt/frame4", 304, 390)},
		{"charactera/clothes/tshirt/frame5", new AtlasInfo("charactera/clothes/tshirt/frame5", 304, 390)},
		{"charactera/clothes/tshirt/frame7", new AtlasInfo("charactera/clothes/tshirt/frame7", 399, 408)},
		{"charactera/clothes/tshirt/frame8", new AtlasInfo("charactera/clothes/tshirt/frame8", 399, 408)},
		{"charactera/clothes/tshirt/frame9", new AtlasInfo("charactera/clothes/tshirt/frame9", 399, 408)},
		{"charactera/face parts/mouths/frame1", new AtlasInfo("charactera/face parts/mouths/frame1", 570, 569)},
		{"charactera/face parts/mouths/frame2", new AtlasInfo("charactera/face parts/mouths/frame2", 570, 569)},
		{"charactera/face parts/mouths/frame1/cheeks mouth closed", new AtlasInfo("charactera/face parts/mouths/frame1/cheeks mouth closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/cheeky smile semi-closed", new AtlasInfo("charactera/face parts/mouths/frame1/cheeky smile semi-closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/chewing smile closed", new AtlasInfo("charactera/face parts/mouths/frame1/chewing smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/miserable closed", new AtlasInfo("charactera/face parts/mouths/frame1/miserable closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/old smile", new AtlasInfo("charactera/face parts/mouths/frame1/old smile", 570, 569)},
		{"charactera/face parts/mouths/frame1/sad closed", new AtlasInfo("charactera/face parts/mouths/frame1/sad closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/smile closed", new AtlasInfo("charactera/face parts/mouths/frame1/smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/smug smile closed", new AtlasInfo("charactera/face parts/mouths/frame1/smug smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/wide smile closed", new AtlasInfo("charactera/face parts/mouths/frame1/wide smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame1/cheeks mouth closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/cheeks mouth closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/cheeky smile semi-closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/cheeky smile semi-closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/chewing smile closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/chewing smile closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/miserable closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/miserable closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/old smile/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/old smile/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/sad closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/sad closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/smile closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/smile closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/smug smile closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/smug smile closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame1/wide smile closed/cropped", new AtlasInfo("charactera/face parts/mouths/frame1/wide smile closed/cropped", 270, 134)},
		{"charactera/face parts/mouths/frame2/cheeks mouth closed", new AtlasInfo("charactera/face parts/mouths/frame2/cheeks mouth closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/cheeky smile semi-closed", new AtlasInfo("charactera/face parts/mouths/frame2/cheeky smile semi-closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/chewing smile closed", new AtlasInfo("charactera/face parts/mouths/frame2/chewing smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/Doraemon lips closed", new AtlasInfo("charactera/face parts/mouths/frame2/Doraemon lips closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/duck lips closed", new AtlasInfo("charactera/face parts/mouths/frame2/duck lips closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/miserable closed", new AtlasInfo("charactera/face parts/mouths/frame2/miserable closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/old smile", new AtlasInfo("charactera/face parts/mouths/frame2/old smile", 570, 569)},
		{"charactera/face parts/mouths/frame2/sad closed", new AtlasInfo("charactera/face parts/mouths/frame2/sad closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/smile closed", new AtlasInfo("charactera/face parts/mouths/frame2/smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/smug smile closed", new AtlasInfo("charactera/face parts/mouths/frame2/smug smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/UwU smile closed", new AtlasInfo("charactera/face parts/mouths/frame2/UwU smile closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/whistling lips semi-closed", new AtlasInfo("charactera/face parts/mouths/frame2/whistling lips semi-closed", 570, 569)},
		{"charactera/face parts/mouths/frame2/wide smile closed", new AtlasInfo("charactera/face parts/mouths/frame2/wide smile closed", 570, 569)},
		{"charactera/face parts/noses/frame1", new AtlasInfo("charactera/face parts/noses/frame1", 570, 569)},
		{"charactera/face parts/noses/frame2", new AtlasInfo("charactera/face parts/noses/frame2", 570, 569)},
		{"charactera/face parts/noses/noses cropped", new AtlasInfo("charactera/face parts/noses/noses cropped", 128, 128)},
		{"charactera/face parts/noses/frame2/long nose", new AtlasInfo("charactera/face parts/noses/frame2/long nose", 570, 569)},
		{"charactera/face parts/noses/frame2/long plump nose", new AtlasInfo("charactera/face parts/noses/frame2/long plump nose", 570, 569)},
		{"charactera/face parts/noses/frame2/long thin nose", new AtlasInfo("charactera/face parts/noses/frame2/long thin nose", 570, 569)},
		{"charactera/face parts/noses/frame2/neutral nose", new AtlasInfo("charactera/face parts/noses/frame2/neutral nose", 570, 569)},
		{"charactera/face parts/noses/frame2/small plump nose", new AtlasInfo("charactera/face parts/noses/frame2/small plump nose", 570, 569)},
		{"charactera/face parts/noses/frame2/square nose", new AtlasInfo("charactera/face parts/noses/frame2/square nose", 570, 569)},
		{"charactera/face parts/noses/frame2/triangular long nose", new AtlasInfo("charactera/face parts/noses/frame2/triangular long nose", 570, 569)},
		{"charactera/face parts/noses/frame2/triangular long plump nose", new AtlasInfo("charactera/face parts/noses/frame2/triangular long plump nose", 570, 569)},
		{"charactera/face parts/noses/frame2/triangular plump nose", new AtlasInfo("charactera/face parts/noses/frame2/triangular plump nose", 570, 569)},
		{"charactera/face parts/noses/frame2/triangular short nose", new AtlasInfo("charactera/face parts/noses/frame2/triangular short nose", 570, 569)},
		{"charactera/face parts/noses/frame2/wide nose", new AtlasInfo("charactera/face parts/noses/frame2/wide nose", 570, 569)},
		{"charactera/face parts/noses/frame2/wide nostril nose", new AtlasInfo("charactera/face parts/noses/frame2/wide nostril nose", 570, 569)},
		{"charactera/face parts/noses/frame2/wide plump nose", new AtlasInfo("charactera/face parts/noses/frame2/wide plump nose", 570, 569)},
		{"charactera/face parts/noses/frame2/wide round plump nose", new AtlasInfo("charactera/face parts/noses/frame2/wide round plump nose", 570, 569)},
		{"charactera/face parts/oczy/frame1/angry_open", new AtlasInfo("charactera/face parts/oczy/frame1/angry_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/beady_open", new AtlasInfo("charactera/face parts/oczy/frame1/beady_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/beta_open", new AtlasInfo("charactera/face parts/oczy/frame1/beta_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/bored_closed", new AtlasInfo("charactera/face parts/oczy/frame1/bored_closed", 570, 569)},
		{"charactera/face parts/oczy/frame1/bored_open", new AtlasInfo("charactera/face parts/oczy/frame1/bored_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/clumsy_open", new AtlasInfo("charactera/face parts/oczy/frame1/clumsy_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/curious_open", new AtlasInfo("charactera/face parts/oczy/frame1/curious_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/evil_open", new AtlasInfo("charactera/face parts/oczy/frame1/evil_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/furious_open", new AtlasInfo("charactera/face parts/oczy/frame1/furious_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/happy_closed", new AtlasInfo("charactera/face parts/oczy/frame1/happy_closed", 570, 569)},
		{"charactera/face parts/oczy/frame1/happy_open", new AtlasInfo("charactera/face parts/oczy/frame1/happy_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/narrowed_open", new AtlasInfo("charactera/face parts/oczy/frame1/narrowed_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/neutral_open", new AtlasInfo("charactera/face parts/oczy/frame1/neutral_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/old_open", new AtlasInfo("charactera/face parts/oczy/frame1/old_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/pleading_open", new AtlasInfo("charactera/face parts/oczy/frame1/pleading_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/sad_closed", new AtlasInfo("charactera/face parts/oczy/frame1/sad_closed", 570, 569)},
		{"charactera/face parts/oczy/frame1/sad_open", new AtlasInfo("charactera/face parts/oczy/frame1/sad_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/scared_closed", new AtlasInfo("charactera/face parts/oczy/frame1/scared_closed", 570, 569)},
		{"charactera/face parts/oczy/frame1/scared_open", new AtlasInfo("charactera/face parts/oczy/frame1/scared_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/serious_open", new AtlasInfo("charactera/face parts/oczy/frame1/serious_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/shocked_open", new AtlasInfo("charactera/face parts/oczy/frame1/shocked_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/smug_open", new AtlasInfo("charactera/face parts/oczy/frame1/smug_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/staring_open", new AtlasInfo("charactera/face parts/oczy/frame1/staring_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/suspicious_open", new AtlasInfo("charactera/face parts/oczy/frame1/suspicious_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/suspicious_semi-open", new AtlasInfo("charactera/face parts/oczy/frame1/suspicious_semi-open", 570, 569)},
		{"charactera/face parts/oczy/frame1/tired_open", new AtlasInfo("charactera/face parts/oczy/frame1/tired_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/winking", new AtlasInfo("charactera/face parts/oczy/frame1/winking", 570, 569)},
		{"charactera/face parts/oczy/frame1/worried_open", new AtlasInfo("charactera/face parts/oczy/frame1/worried_open", 570, 569)},
		{"charactera/face parts/oczy/frame1/bored_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/bored_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame1/clumsy_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/clumsy_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame1/old_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/old_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame1/sad_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/sad_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame1/smug_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/smug_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame1/suspicious_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/suspicious_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame1/suspicious_semi-open/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/suspicious_semi-open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame1/winking/bonus", new AtlasInfo("charactera/face parts/oczy/frame1/winking/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame2/angry_open", new AtlasInfo("charactera/face parts/oczy/frame2/angry_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/beady_open", new AtlasInfo("charactera/face parts/oczy/frame2/beady_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/beta_open", new AtlasInfo("charactera/face parts/oczy/frame2/beta_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/bored_closed", new AtlasInfo("charactera/face parts/oczy/frame2/bored_closed", 570, 569)},
		{"charactera/face parts/oczy/frame2/bored_open", new AtlasInfo("charactera/face parts/oczy/frame2/bored_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/clumsy_open", new AtlasInfo("charactera/face parts/oczy/frame2/clumsy_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/curious_open", new AtlasInfo("charactera/face parts/oczy/frame2/curious_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/evil_open", new AtlasInfo("charactera/face parts/oczy/frame2/evil_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/furious_open", new AtlasInfo("charactera/face parts/oczy/frame2/furious_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/happy_closed", new AtlasInfo("charactera/face parts/oczy/frame2/happy_closed", 570, 569)},
		{"charactera/face parts/oczy/frame2/happy_open", new AtlasInfo("charactera/face parts/oczy/frame2/happy_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/narrowed_open", new AtlasInfo("charactera/face parts/oczy/frame2/narrowed_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/neutral_open", new AtlasInfo("charactera/face parts/oczy/frame2/neutral_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/old_open", new AtlasInfo("charactera/face parts/oczy/frame2/old_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/pleading_open", new AtlasInfo("charactera/face parts/oczy/frame2/pleading_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/sad_closed", new AtlasInfo("charactera/face parts/oczy/frame2/sad_closed", 570, 569)},
		{"charactera/face parts/oczy/frame2/sad_open", new AtlasInfo("charactera/face parts/oczy/frame2/sad_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/scared_closed", new AtlasInfo("charactera/face parts/oczy/frame2/scared_closed", 570, 569)},
		{"charactera/face parts/oczy/frame2/scared_open", new AtlasInfo("charactera/face parts/oczy/frame2/scared_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/serious_open", new AtlasInfo("charactera/face parts/oczy/frame2/serious_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/shocked_open", new AtlasInfo("charactera/face parts/oczy/frame2/shocked_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/smug_open", new AtlasInfo("charactera/face parts/oczy/frame2/smug_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/staring_open", new AtlasInfo("charactera/face parts/oczy/frame2/staring_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/suspicious_open", new AtlasInfo("charactera/face parts/oczy/frame2/suspicious_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/suspicious_semi-open", new AtlasInfo("charactera/face parts/oczy/frame2/suspicious_semi-open", 570, 569)},
		{"charactera/face parts/oczy/frame2/tired_open", new AtlasInfo("charactera/face parts/oczy/frame2/tired_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/winking", new AtlasInfo("charactera/face parts/oczy/frame2/winking", 570, 569)},
		{"charactera/face parts/oczy/frame2/worried_open", new AtlasInfo("charactera/face parts/oczy/frame2/worried_open", 570, 569)},
		{"charactera/face parts/oczy/frame2/bored_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame2/bored_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame2/clumsy_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame2/clumsy_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame2/old_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame2/old_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame2/sad_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame2/sad_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame2/smug_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame2/smug_open/bonus", 570, 569)},
		{"charactera/face parts/oczy/frame2/suspicious_open/bonus", new AtlasInfo("charactera/face parts/oczy/frame2/suspicious_open/bonus", 570, 569)},
		{"charactera/hair/frame1/afro", new AtlasInfo("charactera/hair/frame1/afro", 744, 747)},
		{"charactera/hair/frame1/bald", new AtlasInfo("charactera/hair/frame1/bald", 10, 10)},
		{"charactera/hair/frame1/bob cut", new AtlasInfo("charactera/hair/frame1/bob cut", 638, 630)},
		{"charactera/hair/frame1/curly afroish", new AtlasInfo("charactera/hair/frame1/curly afroish", 768, 711)},
		{"charactera/hair/frame1/fade", new AtlasInfo("charactera/hair/frame1/fade", 572, 631)},
		{"charactera/hair/frame1/fade2", new AtlasInfo("charactera/hair/frame1/fade2", 607, 738)},
		{"charactera/hair/frame1/jheri curl", new AtlasInfo("charactera/hair/frame1/jheri curl", 630, 608)},
		{"charactera/hair/frame1/kok", new AtlasInfo("charactera/hair/frame1/kok", 594, 757)},
		{"charactera/hair/frame1/koki", new AtlasInfo("charactera/hair/frame1/koki", 730, 647)},
		{"charactera/hair/frame1/long hair", new AtlasInfo("charactera/hair/frame1/long hair", 625, 843)},
		{"charactera/hair/frame1/ponytail", new AtlasInfo("charactera/hair/frame1/ponytail", 593, 743)},
		{"charactera/hair/frame1/ponytails", new AtlasInfo("charactera/hair/frame1/ponytails", 793, 660)},
		{"charactera/hair/frame1/puffy hair", new AtlasInfo("charactera/hair/frame1/puffy hair", 780, 735)},
		{"charactera/hair/frame1/short hair", new AtlasInfo("charactera/hair/frame1/short hair", 644, 669)},
		{"charactera/hair/frame1/short hair 2", new AtlasInfo("charactera/hair/frame1/short hair 2", 599, 698)},
		{"charactera/hair/frame1/Velma long hair", new AtlasInfo("charactera/hair/frame1/Velma long hair", 626, 843)},
		{"charactera/hair/frame1/Velma short hair", new AtlasInfo("charactera/hair/frame1/Velma short hair", 638, 630)},
		{"charactera/hair/frame1/very short", new AtlasInfo("charactera/hair/frame1/very short", 591, 579)},
		{"charactera/hair/frame1/wavy long hair", new AtlasInfo("charactera/hair/frame1/wavy long hair", 631, 895)},
		{"charactera/hair/frame1/wavy short hair", new AtlasInfo("charactera/hair/frame1/wavy short hair", 631, 704)},
		{"charactera/hair/frame2/afro", new AtlasInfo("charactera/hair/frame2/afro", 782, 1069)},
		{"charactera/hair/frame2/bald", new AtlasInfo("charactera/hair/frame2/bald", 10, 10)},
		{"charactera/hair/frame2/bob cut", new AtlasInfo("charactera/hair/frame2/bob cut", 782, 1069)},
		{"charactera/hair/frame2/curly afroish", new AtlasInfo("charactera/hair/frame2/curly afroish", 782, 1069)},
		{"charactera/hair/frame2/fade", new AtlasInfo("charactera/hair/frame2/fade", 782, 1069)},
		{"charactera/hair/frame2/fade2", new AtlasInfo("charactera/hair/frame2/fade2", 782, 1069)},
		{"charactera/hair/frame2/jheri curl", new AtlasInfo("charactera/hair/frame2/jheri curl", 782, 1069)},
		{"charactera/hair/frame2/kok", new AtlasInfo("charactera/hair/frame2/kok", 782, 1069)},
		{"charactera/hair/frame2/koki", new AtlasInfo("charactera/hair/frame2/koki", 782, 1069)},
		{"charactera/hair/frame2/long hair", new AtlasInfo("charactera/hair/frame2/long hair", 782, 1069)},
		{"charactera/hair/frame2/ponytail", new AtlasInfo("charactera/hair/frame2/ponytail", 782, 1069)},
		{"charactera/hair/frame2/ponytails", new AtlasInfo("charactera/hair/frame2/ponytails", 782, 1069)},
		{"charactera/hair/frame2/puffy hair", new AtlasInfo("charactera/hair/frame2/puffy hair", 782, 1069)},
		{"charactera/hair/frame2/short hair", new AtlasInfo("charactera/hair/frame2/short hair", 782, 1069)},
		{"charactera/hair/frame2/short hair 2", new AtlasInfo("charactera/hair/frame2/short hair 2", 782, 1069)},
		{"charactera/hair/frame2/Velma long hair", new AtlasInfo("charactera/hair/frame2/Velma long hair", 782, 1069)},
		{"charactera/hair/frame2/Velma short hair", new AtlasInfo("charactera/hair/frame2/Velma short hair", 782, 1069)},
		{"charactera/hair/frame2/very short", new AtlasInfo("charactera/hair/frame2/very short", 782, 1069)},
		{"charactera/hair/frame2/wavy long hair", new AtlasInfo("charactera/hair/frame2/wavy long hair", 782, 1069)},
		{"charactera/hair/frame2/wavy short hair", new AtlasInfo("charactera/hair/frame2/wavy short hair", 782, 1069)},
		{"charactera/hair/frame3/afro", new AtlasInfo("charactera/hair/frame3/afro", 793, 1021)},
		{"charactera/hair/frame3/bald", new AtlasInfo("charactera/hair/frame3/bald", 10, 10)},
		{"charactera/hair/frame3/bob cut", new AtlasInfo("charactera/hair/frame3/bob cut", 793, 1021)},
		{"charactera/hair/frame3/curly afroish", new AtlasInfo("charactera/hair/frame3/curly afroish", 793, 1021)},
		{"charactera/hair/frame3/fade", new AtlasInfo("charactera/hair/frame3/fade", 793, 1021)},
		{"charactera/hair/frame3/fade2", new AtlasInfo("charactera/hair/frame3/fade2", 793, 1021)},
		{"charactera/hair/frame3/jheri curl", new AtlasInfo("charactera/hair/frame3/jheri curl", 793, 1021)},
		{"charactera/hair/frame3/kok", new AtlasInfo("charactera/hair/frame3/kok", 793, 1021)},
		{"charactera/hair/frame3/koki", new AtlasInfo("charactera/hair/frame3/koki", 793, 1021)},
		{"charactera/hair/frame3/long hair", new AtlasInfo("charactera/hair/frame3/long hair", 793, 1021)},
		{"charactera/hair/frame3/ponytail", new AtlasInfo("charactera/hair/frame3/ponytail", 793, 1021)},
		{"charactera/hair/frame3/ponytails", new AtlasInfo("charactera/hair/frame3/ponytails", 793, 1021)},
		{"charactera/hair/frame3/puffy hair", new AtlasInfo("charactera/hair/frame3/puffy hair", 793, 1021)},
		{"charactera/hair/frame3/short hair", new AtlasInfo("charactera/hair/frame3/short hair", 793, 1021)},
		{"charactera/hair/frame3/short hair 2", new AtlasInfo("charactera/hair/frame3/short hair 2", 793, 1021)},
		{"charactera/hair/frame3/Velma long hair", new AtlasInfo("charactera/hair/frame3/Velma long hair", 793, 1021)},
		{"charactera/hair/frame3/Velma short hair", new AtlasInfo("charactera/hair/frame3/Velma short hair", 793, 1021)},
		{"charactera/hair/frame3/very short", new AtlasInfo("charactera/hair/frame3/very short", 793, 1021)},
		{"charactera/hair/frame3/wavy long hair", new AtlasInfo("charactera/hair/frame3/wavy long hair", 793, 1021)},
		{"charactera/hair/frame3/wavy short hair", new AtlasInfo("charactera/hair/frame3/wavy short hair", 793, 1021)},
	};
}
